C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2.0.0)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapcomph0 (comph0f2pywrap, neqn, dy, tbegin,
     & tend, tolvec, rtol, atol, indgt1, ind)
      external comph0
      integer neqn
      double precision tbegin
      double precision tend
      logical tolvec
      logical indgt1
      double precision dy(neqn)
      double precision rtol(*)
      double precision atol(*)
      integer ind(*)
      double precision comph0f2pywrap
      double precision  comph0
      comph0f2pywrap = comph0(neqn, dy, tbegin, tend, tolvec, rtol
     &, atol, indgt1, ind)
      end


      subroutine f2pywrapsnorm (snormf2pywrap, neqn, y, ynorm, h, 
     &tolvec, rtol, atol, indgt1, ind)
      external snorm
      integer neqn
      double precision h
      logical tolvec
      logical indgt1
      double precision y(neqn)
      double precision ynorm(neqn)
      double precision rtol(*)
      double precision atol(*)
      integer ind(*)
      double precision snormf2pywrap
      double precision  snorm
      snormf2pywrap = snorm(neqn, y, ynorm, h, tolvec, rtol, atol,
     & indgt1, ind)
      end


      subroutine f2pywrapsnorms (snormsf2pywrap, neqn, y, ysnorm, 
     &h, tolvec, rtol, atol, indgt1, ind)
      external snorms
      integer neqn
      double precision h
      logical tolvec
      logical indgt1
      double precision y(neqn)
      double precision ysnorm(neqn,4)
      double precision rtol(*)
      double precision atol(*)
      integer ind(*)
      double precision snormsf2pywrap
      double precision  snorms
      snormsf2pywrap = snorms(neqn, y, ysnorm, h, tolvec, rtol, at
     &ol, indgt1, ind)
      end

